### ISSUE TITLE
Forked gems and hacks still necessary?

### ISSUE THREAD

**Issue by mfaerevaag** [ibikecph/ibikecph-site#4]
Hey! Awesome app you've made. I'm going to be doing some work on the project, so I'm going to be asking some questions just to get up to speed with the code base.. :-)

They are mainly about some forked gems which have fallen behind their upstreams and are becoming a pain to maintain. Also, an hack which I can't wrap my head around.

`auto_html`: 
This [commit](https://github.com/emiltin/auto_html/commit/4633754ce8907b8f2994ae56fbab4f8a11fb40bb) fixes some gsub problem in the auto_html gem. Can anyone remember how to recreate the problem? Asking because it is a pain keeping a forked gem up to date with upstream. Therefore it would be great if the problem "went away" or to submit a pull-request to upstream.

`cancan`:
Same thing as above, really.

`config/initializers/acts_as_taggable_on_hacks.rb`:
Not really sure what the [acts_as_taggable_on_hacks.rb](https://github.com/ibikecph/ibikecph-site/blob/master/config/initializers/acts_as_taggable_on_hacks.rb) is good for, but I can't seem to get it to run with it not being commented out. What does it do? :-)

**Comment by emiltin** [comment]
can i close this?

**Comment by mfaerevaag** [comment]
Yes, thank you
