### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by emiltin** [ibikecph/ibikecph-site#48]
Check that we don't send data to GA that identify a user, like email or locations.

**Comment by NCdpac** [comment]
Update: There are no direct code segments that decide specifically which data is sweeped by GA, this can however be changed in the GA management interface, by adding filters that sort away any data that matches email adresses or locations.

In order to make further progress on this, I will need access to the google analytics management interface.

**Comment by emiltin** [comment]
We're deleting our current GA account. Instead we will setup a new account. However, it looks like Google Analytics is depreciated in favour of Google Analytics for Firebase, which is a different product/api. If you can confirm this, then first step might be to remove GA. 
In any case, we don't want to send things like email, and later filter at the GA end. It should not be send at all. cc @Truhoan

**Comment by emiltin** [comment]
Chrome console shows no email being send when logging in on the site. The url is send, and includes any query parameters, but I don't think emails, passwords or locations are ever in query params. When linking to routes, the url will look like this: https://www.ibikecph.dk/#!/x5eo0.7h1vx//mode:fast. But the url send to GA only includes https://www.ibikecph.dk/, not the location part (which is parsed by the backbone js front-end code).

**Comment by emiltin** [comment]
let's remove it completely. later we can add google analytics for firebase.

**Comment by NCdpac** [comment]
Update: A branch has been created to house the changes to remove the google analytics plugin

**Comment by emiltin** [comment]
done
